version: '3.8'

services:
  mongo:
    image: mongo
    container_name: hostel_mongo
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  server:
    build: ./backend
    container_name: hostel_backend
    restart: always
    ports:
      - "3000:3000"
    depends_on:
      - mongo
    environment:
      - MONGO_URI=mongodb://mongo:27017/hostel
      - JWT_SECRET=Anappleadaykeepsthedoctoraway

  frontend:
    build: ./client
    container_name: hostel_frontend
    ports:
      - "5173:5173"
    depends_on:
      - server

volumes:
  mongo-data:
